#!/bin/bash
# ----------------------------------------------------------------------
# Ericsson Network IQ ETLC engine control script for SMF to use
#
# Usage: engine start|stop
#
# ----------------------------------------------------------------------
# Copyright (c) 1999 - 2007 AB Ericsson Oy  All rights reserved.
# ----------------------------------------------------------------------

unalias stop 2> /dev/null

if [ -z "${CONF_DIR}" ] ; then
  echo "ERROR: CONF_DIR is not set"
  exit 1
fi

. ${CONF_DIR}/niq.rc

_dir_=`/usr/bin/dirname $0`
SCRIPTHOME=`cd $_dir_ 2>/dev/null && pwd || echo $_dir_`

if [ -s $SCRIPTHOME/../lib/common_functions.lib ]; then
    . $SCRIPTHOME/../lib/common_functions.lib
else
        echo "Could not find $SCRIPTHOME/../lib/common_functions.lib"
        exit 63
fi

ETLC_USER=`iniget ETLC -v UserName -f ${CONF_DIR}/niq.ini`

if [ ${LOGNAME} != ${ETLC_USER} ] ; then
  echo "ETLC engine must be started as user ${ETLC_USER}"
  exit 32
fi

JAVA_HOME="/eniq/sw/runtime/java"

CPATH="${PLATFORM_DIR}"

DIRS=`ls ${PLATFORM_DIR}`

for file in ${DIRS}
do
  if [ -d ${PLATFORM_DIR}/${file}/dclib ]
  then
    JARS=`ls ${PLATFORM_DIR}/${file}/dclib/*.jar`

    for jar in ${JARS}
    do
      CPATH="${CPATH}:${jar}"
    done
  fi
done

start() {

  if [ ! -d ${LOG_DIR}/engine ] ; then
    mkdir ${LOG_DIR}/engine
  fi

  LOGFILE=${LOG_DIR}/engine/start_engine_`date '+%y%m%d_%H%M%S'`.log

  echo "Starting ETLC engine..." > ${LOGFILE}

  xENG=`ps -ef | grep java | grep "pname=ETLCEngine" | awk '{print $2}'`
  if [ ! -z "${xENG}" ] ; then
    echo "Killing previous engine instance in PID ${xENG}" >> ${LOGFILE}
    kill -9 ${xENG} 2>&1 | tee -a ${LOGFILE}
    echo "Previous engine killed" >> ${LOGFILE}
  fi

  xSCH=`ps -ef | grep java | grep "pname=ETLCScheduler" | awk '{print $2}'`
  if [ ! -z "${xSCH}" ] ; then
    echo "Killing previous scheduler instance in PID ${xSCH}" >> ${LOGFILE}
    kill -9 ${xSCH} 2>&1 | tee -a ${LOGFILE}
    echo "Previous scheduler killed" >> ${LOGFILE}
  fi

  HEAP_SIZE=`iniget ETLC -v EngineHeap -f ${CONF_DIR}/niq.ini`
  CPU_CORES=`iniget ENIQ_HW_INFO -v Eniq_Proc_Core -f ${CONF_DIR}/niq.ini`

  ${JAVA_HOME}/bin/java -d64 -Dpname="ETLCEngine" -mx${HEAP_SIZE} -Djava.util.logging.config.file=${CONF_DIR}/engineLogging.properties -Dlog4j.configuration=file:${CONF_DIR}/engine.log4j.properties -Ddc5000.config.directory=${CONF_DIR} -DCONF_DIR=${CONF_DIR} -DPMDATA_DIR=${PMDATA_DIR} -DETLDATA_DIR=${ETLDATA_DIR} -DFMDATA_DIR=${FMDATA_DIR} -DLOG_DIR=${LOG_DIR} -DREJECTED_DIR=${REJECTED_DIR} -DREFERENCE_DIR=${REFERENCE_DIR} -DPLATFORM_DIR=${PLATFORM_DIR} -DARCHIVE_DIR=${ARCHIVE_DIR} -DCPU_CORES=${CPU_CORES} -DHEAP_SIZE=${HEAP_SIZE} -server -classpath ${CPATH} com.distocraft.dc5000.etl.engine.main.TransferEngine &

  echo "engine forked" >> ${LOGFILE}

  START_COUNT=`iniget ETLC -v EngineStartCount -f ${CONF_DIR}/niq.ini`
  START_DELAY=`iniget ETLC -v EngineStartDelay -f ${CONF_DIR}/niq.ini`

  cnt=0

  while [ ${cnt} -lt ${START_COUNT} ] ; do
    sleep ${START_DELAY}

    echo "Checking engine status..." >> ${LOGFILE}
    ${BIN_DIR}/engine status >> ${LOGFILE} 2>&1

    if [ $? -eq 0 ] ; then
      echo "ETLC engine succesfully started" >> ${LOGFILE}
      exit 0     
    else
      echo "engine not started yet" >> ${LOGFILE}
      let cnt=cnt+1
    fi

  done

  echo "ETLC engine failed to start" >> ${LOGFILE}

  exit 55

}

stop() {
  
  LOGFILE=${LOG_DIR}/engine/stop_engine_`date '+%y%m%d_%H%M%S'`.log

  echo "Stopping ETLC engine..." > ${LOGFILE}

  ${JAVA_HOME}/bin/java -Dpname="EngineAdmin" -mx64M -Djava.util.logging.config.file=${CONF_DIR}/engineAdminLogging.properties -Ddc5000.config.directory=${CONF_DIR} -Ddc.conf.dir=${CONF_DIR} -DLOG_DIR=${LOG_DIR} -classpath ${CPATH} com.distocraft.dc5000.etl.engine.main.EngineAdmin stop

  echo "ETLC engine shutdown requested" >> ${LOGFILE}

  STOP_COUNT=`iniget ETLC -v EngineStopCount -f ${CONF_DIR}/niq.ini`
  STOP_DELAY=`iniget ETLC -v EngineStopDelay -f ${CONF_DIR}/niq.ini`

  cnt=0

  while [ ${cnt} -lt ${STOP_COUNT} ] ; do
    sleep ${STOP_DELAY}

    echo "Checking engine status..." >> ${LOGFILE}
    ePID=`ps -ef | grep java | grep ETLCEngine | awk '{print $2}'`

    if [ -z "${ePID}" ] ; then
      echo "ETLC engine shutdown is complete" >> ${LOGFILE}
      exit 0
    else
      echo "engine is still running" >> ${LOGFILE}
      let cnt=cnt+1
    fi

  done

  ePID=`ps -ef | grep java | grep ETLCEngine | awk '{print $2}'`

  echo "ETLC engine refused to stop trying to kill it." >> ${LOGFILE}

  if [ ! -z "${ePID}" ] ; then
    kill -9 ${ePID}
    echo "ETLC engine killed." >> ${LOGFILE}
  else
    echo "ELTC engine was dead before killing" >> ${LOGFILE}
  fi

  exit 0

}

case "$1" in
start)
      start
      ;;
stop)
     stop
     ;;
*)
     echo "This script shall only be used by SMF!"
     exit 10
     ;;
esac
