/*==============================================================*/
/* etlrep Forigen Keys	                                        */
/*==============================================================*/
ALTER TABLE etlrep.META_EXECUTION_SLOT ADD CONSTRAINT PAR_VEN_FK FOREIGN KEY (PROFILE_ID) REFERENCES etlrep.META_EXECUTION_SLOT_PROFILE(PROFILE_ID);
ALTER TABLE etlrep.META_TRANSFORMATION_RULES ADD CONSTRAINT TRE_VEN_FK FOREIGN KEY (VERSION_NUMBER) REFERENCES etlrep.META_VERSIONS(VERSION_NUMBER) ;

ALTER TABLE etlrep.META_COLUMNS ADD CONSTRAINT COMN_TAE_FK FOREIGN KEY (
    VERSION_NUMBER,CONNECTION_ID,
    TABLE_ID) REFERENCES etlrep.META_TABLES(
    VERSION_NUMBER,CONNECTION_ID,
   TABLE_ID) ;
   
ALTER TABLE etlrep.META_DEBUGS ADD CONSTRAINT DEG_TAN_FK FOREIGN KEY (
    VERSION_NUMBER,
    COLLECTION_SET_ID,COLLECTION_ID,TRANSFER_ACTION_ID) REFERENCES etlrep.META_TRANSFER_ACTIONS(VERSION_NUMBER,
    COLLECTION_SET_ID,COLLECTION_ID,TRANSFER_ACTION_ID) ;

ALTER TABLE etlrep.META_FK_TABLE_JOINTS ADD CONSTRAINT FTJT_FTE_FK FOREIGN KEY (VERSION_NUMBER, 
COLLECTION_SET_ID, COLLECTION_ID, TRANSFER_ACTION_ID, CONNECTION_ID, TABLE_ID, TARGET_TABLE_ID)
 REFERENCES etlrep.META_FK_TABLES(VERSION_NUMBER, 
COLLECTION_SET_ID, COLLECTION_ID, TRANSFER_ACTION_ID, CONNECTION_ID, TABLE_ID, TARGET_TABLE_ID) ;

ALTER TABLE etlrep.META_FK_TABLE_JOINTS ADD CONSTRAINT FTJT_COMN_FK FOREIGN KEY (VERSION_NUMBER,
   CONNECTION_ID,TARGET_TABLE_ID,
   COLUMN_ID) REFERENCES etlrep.META_COLUMNS(VERSION_NUMBER,
   CONNECTION_ID,TABLE_ID,
   COLUMN_ID
   ) ;

ALTER TABLE etlrep.META_TRANSF_TABLE_VALUES ADD CONSTRAINT TTVE_TTE_FK FOREIGN KEY (
    VERSION_NUMBER,TRANSF_TABLE_ID) REFERENCES etlrep.META_TRANSFORMATION_TABLES(VERSION_NUMBER,TRANSF_TABLE_ID) ;

ALTER TABLE etlrep.META_SQL_LOADS ADD CONSTRAINT SLD_TATE_FK FOREIGN KEY (VERSION_NUMBER,COLLECTION_SET_ID,
    COLLECTION_ID,TRANSFER_ACTION_ID,
    CONNECTION_ID,
    TABLE_ID) REFERENCES etlrep.META_TARGET_TABLES(VERSION_NUMBER,COLLECTION_SET_ID,
    COLLECTION_ID,TRANSFER_ACTION_ID,
    CONNECTION_ID,
    TABLE_ID) ;


ALTER TABLE etlrep.META_TRANSFORMATION_TABLES ADD CONSTRAINT TTE_VEN_FK FOREIGN KEY (VERSION_NUMBER) REFERENCES etlrep.META_VERSIONS(VERSION_NUMBER) ;

ALTER TABLE etlrep.META_TRANSFORMATION_TABLES ADD CONSTRAINT TTE_COMN_KEY_FK FOREIGN KEY (VERSION_NUMBER,
    CONNECTION_ID,
    TABLE_ID,
    KEY_COLUMN_ID) REFERENCES etlrep.META_COLUMNS(VERSION_NUMBER,
   CONNECTION_ID,
   TABLE_ID,
   COLUMN_ID) ;

ALTER TABLE etlrep.META_TRANSFORMATION_TABLES ADD CONSTRAINT TTE_COMN_VAL_FK FOREIGN KEY (VERSION_NUMBER,
    CONNECTION_ID,
    TABLE_ID,
    VALUE_COLUMN_ID) REFERENCES etlrep.META_COLUMNS(VERSION_NUMBER,
   CONNECTION_ID,
   TABLE_ID,
   COLUMN_ID) ;

ALTER TABLE etlrep.META_PARAMETERS ADD CONSTRAINT PAR_VEN_FK FOREIGN KEY (VERSION_NUMBER) REFERENCES etlrep.META_VERSIONS(VERSION_NUMBER) ;

ALTER TABLE etlrep.META_PARAMETER_TABLES ADD CONSTRAINT PTE_VEN_FK FOREIGN KEY (VERSION_NUMBER) REFERENCES etlrep.META_VERSIONS(VERSION_NUMBER) ;

ALTER TABLE etlrep.META_TRANSFER_ACTIONS ADD CONSTRAINT TAN_CON_FK FOREIGN KEY (VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID) REFERENCES etlrep.META_COLLECTIONS(VERSION_NUMBER,
   COLLECTION_SET_ID,
   COLLECTION_ID) ;

ALTER TABLE etlrep.META_TABLES ADD CONSTRAINT TAE_DAE_FK FOREIGN KEY (VERSION_NUMBER,
    CONNECTION_ID) REFERENCES etlrep.META_DATABASES(VERSION_NUMBER,
   CONNECTION_ID) ;

ALTER TABLE etlrep.META_STATUSES ADD CONSTRAINT STS_TAN_FK FOREIGN KEY (VERSION_NUMBER,
COLLECTION_SET_ID, COLLECTION_ID,TRANSFER_ACTION_ID) REFERENCES etlrep.META_TRANSFER_ACTIONS(VERSION_NUMBER,
COLLECTION_SET_ID, COLLECTION_ID,TRANSFER_ACTION_ID) ;

ALTER TABLE etlrep.META_COLUMN_CONSTRAINTS ADD CONSTRAINT CCT_COMN_FK FOREIGN KEY (
    VERSION_NUMBER,CONNECTION_ID,TABLE_ID,
    COLUMN_ID
    ) REFERENCES etlrep.META_COLUMNS(VERSION_NUMBER,CONNECTION_ID,TABLE_ID,
    COLUMN_ID
    ) ;

ALTER TABLE etlrep.META_FILES ADD CONSTRAINT FILE_1_TAN_FK FOREIGN KEY (VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID) REFERENCES etlrep.META_TRANSFER_ACTIONS(VERSION_NUMBER,
   COLLECTION_SET_ID,
   COLLECTION_ID,
   TRANSFER_ACTION_ID) ;

ALTER TABLE etlrep.META_FK_TABLES ADD CONSTRAINT FTE_TATE_FK FOREIGN KEY (
    VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID,
    CONNECTION_ID,
   TARGET_TABLE_ID) REFERENCES etlrep.META_TARGET_TABLES(VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID,
    CONNECTION_ID,
    TABLE_ID) ;

ALTER TABLE etlrep.META_FK_TABLES ADD CONSTRAINT FTE_TAE_FK FOREIGN KEY (VERSION_NUMBER,
    CONNECTION_ID,TARGET_TABLE_ID
    ) REFERENCES etlrep.META_TABLES(VERSION_NUMBER,
    CONNECTION_ID,TABLE_ID) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_PLUG_FK FOREIGN KEY (
    VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID,PLUGIN_ID) REFERENCES etlrep.META_PLUGINS(VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID,PLUGIN_ID) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_STE_FK FOREIGN KEY (VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID,
    SOURCE_CONNECTION_ID,
    SOURCE_TABLE_ID) REFERENCES etlrep.META_SOURCE_TABLES(VERSION_NUMBER,
   COLLECTION_SET_ID,
   COLLECTION_ID,
   TRANSFER_ACTION_ID,
   CONNECTION_ID,
   TABLE_ID) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_COMN_FK FOREIGN KEY (VERSION_NUMBER,
    TARGET_CONNECTION_ID,
    TARGET_TABLE_ID,
    COLUMN_ID_TARGET_COLUMN) REFERENCES etlrep.META_COLUMNS(VERSION_NUMBER,
   CONNECTION_ID,
   TABLE_ID,
   COLUMN_ID) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_COMN_SOURCE_COLUMN_FK FOREIGN KEY (VERSION_NUMBER,
    SOURCE_CONNECTION_ID,SOURCE_TABLE_ID,
    COLUMN_ID_SOURCE_COLUMN) REFERENCES etlrep.META_COLUMNS(VERSION_NUMBER,
   CONNECTION_ID,
   TABLE_ID,
   COLUMN_ID) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_TRE_FK FOREIGN KEY (VERSION_NUMBER,TRANSFORMATION_ID
    ) REFERENCES etlrep.META_TRANSFORMATION_RULES(VERSION_NUMBER,TRANSFORMATION_ID) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_TTE_FK FOREIGN KEY (VERSION_NUMBER,TRANSF_TABLE_ID
    ) REFERENCES etlrep.META_TRANSFORMATION_TABLES(VERSION_NUMBER,TRANSF_TABLE_ID) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_TATE_FK FOREIGN KEY (VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID,
    TARGET_CONNECTION_ID,
    TARGET_TABLE_ID) REFERENCES etlrep.META_TARGET_TABLES(VERSION_NUMBER,
   COLLECTION_SET_ID,
   COLLECTION_ID,
   TRANSFER_ACTION_ID,
   CONNECTION_ID,
   TABLE_ID) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_PTE_FK FOREIGN KEY (VERSION_NUMBER,PAR_NAME
    ) REFERENCES etlrep.META_PARAMETER_TABLES(VERSION_NUMBER,PAR_NAME) ;

ALTER TABLE etlrep.META_JOINTS ADD CONSTRAINT JOT_FILE_1_FK FOREIGN KEY (
    VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID,FILE_ID) REFERENCES etlrep.META_FILES(
   VERSION_NUMBER,
   COLLECTION_SET_ID,
   COLLECTION_ID,
   TRANSFER_ACTION_ID,FILE_ID) ;

ALTER TABLE etlrep.META_SOURCE_TABLES ADD CONSTRAINT STE_TAE_FK FOREIGN KEY (
    VERSION_NUMBER,CONNECTION_ID,
    TABLE_ID) REFERENCES etlrep.META_TABLES(
    VERSION_NUMBER,CONNECTION_ID,
    TABLE_ID) ;

ALTER TABLE etlrep.META_SOURCE_TABLES ADD CONSTRAINT STE_TAN_FK FOREIGN KEY (
    VERSION_NUMBER,
    COLLECTION_SET_ID,COLLECTION_ID,TRANSFER_ACTION_ID) REFERENCES etlrep.META_TRANSFER_ACTIONS(VERSION_NUMBER,
    COLLECTION_SET_ID,COLLECTION_ID,TRANSFER_ACTION_ID) ;

ALTER TABLE etlrep.META_SOURCE_TABLES ADD CONSTRAINT STE_COMN_FK FOREIGN KEY (VERSION_NUMBER,CONNECTION_ID,
    TABLE_ID,
    TIMESTAMP_COLUMN_ID
    ) REFERENCES etlrep.META_COLUMNS(VERSION_NUMBER,CONNECTION_ID,TABLE_ID,
   COLUMN_ID) ;

ALTER TABLE etlrep.META_DATABASES ADD CONSTRAINT DAE_VEN_FK FOREIGN KEY (VERSION_NUMBER) REFERENCES etlrep.META_VERSIONS(VERSION_NUMBER) ;

ALTER TABLE etlrep.META_DATABASES ADD CONSTRAINT DAE_CTE_FK FOREIGN KEY (TYPE_NAME) REFERENCES etlrep.META_CONNECTION_TYPES(TYPE_NAME) ;

ALTER TABLE etlrep.META_COLLECTIONS ADD CONSTRAINT CON_CST_FK FOREIGN KEY (VERSION_NUMBER,
    COLLECTION_SET_ID) REFERENCES etlrep.META_COLLECTION_SETS(VERSION_NUMBER,
   COLLECTION_SET_ID) ;

ALTER TABLE etlrep.META_ERRORS ADD CONSTRAINT ERR_TAN_FK FOREIGN KEY (VERSION_NUMBER,
    COLLECTION_SET_ID,COLLECTION_ID,
    TRANSFER_ACTION_ID
    ) REFERENCES etlrep.META_TRANSFER_ACTIONS(VERSION_NUMBER,
    COLLECTION_SET_ID,COLLECTION_ID,
    TRANSFER_ACTION_ID) ;

ALTER TABLE etlrep.META_PLUGINS ADD CONSTRAINT PLUG_TAN_FK FOREIGN KEY (VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID) REFERENCES etlrep.META_TRANSFER_ACTIONS(VERSION_NUMBER,
   COLLECTION_SET_ID,
   COLLECTION_ID,
   TRANSFER_ACTION_ID) ;

ALTER TABLE etlrep.META_TARGET_TABLES ADD CONSTRAINT TATE_TAE_FK FOREIGN KEY (VERSION_NUMBER,CONNECTION_ID,
    TABLE_ID) REFERENCES etlrep.META_TABLES(VERSION_NUMBER,CONNECTION_ID,
    TABLE_ID) ;

ALTER TABLE etlrep.META_TARGET_TABLES ADD CONSTRAINT TATE_TAN_FK FOREIGN KEY (VERSION_NUMBER,
    COLLECTION_SET_ID,
    COLLECTION_ID,
    TRANSFER_ACTION_ID) REFERENCES etlrep.META_TRANSFER_ACTIONS(VERSION_NUMBER,
   COLLECTION_SET_ID,
   COLLECTION_ID,
   TRANSFER_ACTION_ID) ;
   
   
ALTER TABLE etlrep.META_SYSTEM_MONITORS ADD CONSTRAINT FK_META_SYS_REFERENCE_META_SER FOREIGN KEY (HOSTNAME) REFERENCES etlrep.META_SERVERS(HOSTNAME);
